export const mappingVCardToListingType = (type: string): string => {
    const mapping: { [key: string]: string } = {
        // See types
        'old town': 'see',
        'amphitheater': 'see',
        'aqueduct': 'see',
        'archaeological site': 'see',
        'architecture': 'see',
        'archive': 'see',
        'bridge': 'see',
        'building': 'see',
        'castle': 'see',
        'cemetery': 'see',
        'chateau': 'see',
        'church': 'see',
        'city wall': 'see',
        'communication tower': 'see',
        'cultural heritage': 'see',
        'fort': 'see',
        'fountain': 'see',
        'gallery': 'see',
        'ghost town': 'see',
        'handicraft': 'see',
        'historic district': 'see',
        'house': 'see',
        'lighthouse': 'see',
        'memorial': 'see',
        'mine': 'see',
        'mining museum': 'see',
        'monastery': 'see',
        'monument': 'see',
        'mosque': 'see',
        'museum': 'see',
        'observation tower': 'see',
        'palace': 'see',
        'planetarium': 'see',
        'ruins': 'see',
        'scenic view': 'see',
        'statue': 'see',
        'synagogue': 'see',
        'temple': 'see',
        'tower': 'see',
        'town hall': 'see',
        'viewpoint': 'see',
        'war grave': 'see',
        'watermill': 'see',
        'windmill': 'see',
        'zoo': 'see',
        'view': 'see',
        'nature': 'see',
        'see': 'see',
        'château': 'see',


        // Activities
        'do': 'do',
        'arena': 'do',
        'attraction': 'do',
        'ballooning': 'do',
        'basketball court': 'do',
        'beachvolleyball': 'do',
        'billiards': 'do',
        'bmx': 'do',
        'bobsleigh': 'do',
        'boat rental': 'do',
        'boules': 'do',
        'bowling': 'do',
        'bungee jumping': 'do',
        'cabaret': 'do',
        'canoe': 'do',
        'canyoning': 'do',
        'casino': 'do',
        'cinema': 'do',
        'climbing': 'do',
        'concert hall': 'do',
        'conference center': 'do',
        'cooking class': 'do',
        'cricket': 'do',
        'cultural center': 'do',
        'cycling': 'do',
        'diving': 'do',
        'dolphinarium': 'do',
        'escape game': 'do',
        'event': 'do',
        'extreme sports': 'do',
        'festival': 'do',
        'fishing': 'do',
        'fitness center': 'do',
        'football pitch': 'do',
        'gliding': 'do',
        'golf': 'do',
        'hiking': 'do',
        'hillwalking': 'do',
        'horse riding': 'do',
        'ice rink': 'do',
        'ice skating': 'do',
        'ice stadium': 'do',
        'indoor pool': 'do',
        'kitesurfing': 'do',
        'karting': 'do',
        'leisure center': 'do',
        'massage': 'do',
        'mountain biking': 'do',
        'outdoor pool': 'do',
        'parachuting': 'do',
        'paragliding': 'do',
        'playground': 'do',
        'public bath': 'do',
        'rafting': 'do',
        'ropes course': 'do',
        'rowing': 'do',
        'sailing': 'do',
        'sandboarding': 'do',
        'sauna': 'do',
        'scuba diving': 'do',
        'shooting range': 'do',
        'skatepark': 'do',
        'skiing': 'do',
        'ski school': 'do',
        'ski touring': 'do',
        'skydiving': 'do',
        'sledding': 'do',
        'snorkeling': 'do',
        'snowboarding': 'do',
        'soccer': 'do',
        'spa': 'do',
        'squash': 'do',
        'summer toboggan': 'do',
        'surfing': 'do',
        'swimming': 'do',
        'tennis': 'do',
        'theme park': 'do',
        'toboggan': 'do',
        'water park': 'do',
        'water sports': 'do',
        'wellness': 'do',
        'wildlife observation': 'do',
        'windsurfing': 'do',
        'winter sports': 'do',
        'yoga': 'do',

        // Shopping
        'antiquarian': 'buy',
        'bakery': 'buy',
        'bank': 'buy',
        'beverages': 'buy',
        'bike shop': 'buy',
        'book seller': 'buy',
        'boutique': 'buy',
        'butchery': 'buy',
        'car repair': 'buy',
        'carpet shop': 'buy',
        'chemist': 'buy',
        'clothes': 'buy',
        'collectibles': 'buy',
        'convenience': 'buy',
        'crafts shop': 'buy',
        'delicatessen': 'buy',
        'department store': 'buy',
        'duty-free shop': 'buy',
        'electronics': 'buy',
        'fashion store': 'buy',
        'florist': 'buy',
        'gift shop': 'buy',
        'grocery': 'buy',
        'hardware': 'buy',
        'jewellery': 'buy',
        'kiosk': 'buy',
        'mall': 'buy',
        'market': 'buy',
        'music shop': 'buy',
        'optician': 'buy',
        'outdoor retailer': 'buy',
        'pastry shop': 'buy',
        'perfumery': 'buy',
        'pet shop': 'buy',
        'photo store': 'buy',
        'second hand': 'buy',
        'shoe shop': 'buy',
        'shopping district': 'buy',
        'shopping street': 'buy',
        'souvenir shop': 'buy',
        'sports shop': 'buy',
        'supermarket': 'buy',
        'ticket shop': 'buy',
        'toys': 'buy',
        'vending machine': 'buy',
        'wine shop': 'buy',


        // Accommodation
        'appartment': 'sleep',
        'alpine hut': 'sleep',
        'bed and bike': 'sleep',
        'bnb': 'sleep',
        'campsite': 'sleep',
        'caravan site': 'sleep',
        'chalet': 'sleep',
        'ecolodge': 'sleep',
        'guest house': 'sleep',
        'hostel': 'sleep',
        'hotel': 'sleep',
        'hotel garni': 'sleep',
        'holiday flat': 'sleep',
        'motel': 'sleep',
        'resort': 'sleep',
        'wilderness hut': 'sleep',
        'youth hostel': 'sleep',
        'boarding house': 'sleep',

        // Eating
        'bistro': 'eat',
        'brasserie': 'eat',
        'cafeteria': 'eat',
        'cafe': 'eat',
        'fast food': 'eat',
        'ice cream': 'eat',
        'pizzeria': 'eat',
        'restaurant': 'eat',
        'seafood restaurant': 'eat',
        'snack bar': 'eat',
        'street food': 'eat',
        'takeaway': 'eat',
        'tavern': 'eat',
        'teahouse': 'eat',

        // Nightlife
        'bar': 'drink',
        'beer garden': 'drink',
        'brewery': 'drink',
        'club': 'drink',
        'discotheque': 'drink',
        'nightclub': 'drink',
        'pub': 'drink',
        'wine bar': 'drink',


        // Other and generic
        'other': 'listing',
        'health': 'listing',
        'go': 'listing',
        'error': 'listing',
        'area': 'listing',
        'populated': 'listing',
        'religion': 'listing',

    };
// Default to 'listing' if no specific match is found
    return mapping[type.toLowerCase()] || 'listing';
}
//
// const mapListingTypeToVCards = (type: string): string[] => {
//     const mapping = {
//         'see': ['old town', 'amphitheater', 'aqueduct', 'archaeological site', 'archaeological site', 'architecture', 'archive', 'bridge', 'building', 'castle', 'cemetery', 'chateau', 'church', 'city wall', 'communication tower', 'cultural heritage', 'fort', 'fountain', 'gallery', 'ghost town', 'handicraft', 'historic district', 'house', 'lighthouse', 'memorial', 'mine', 'mining museum', 'monastery', 'monument', 'mosque', 'museum', 'observation tower', 'palace', 'planetarium', 'ruins', 'scenic view', 'statue', 'synagogue', 'temple', 'tower', 'town hall', 'viewpoint', 'war grave', 'watermill', 'windmill', 'zoo', 'view', 'nature', 'see', 'château'],
//         'do': ['do', 'arena', 'attraction', 'ballooning', 'basketball court', 'beachvolleyball', 'billiards', 'bmx', 'bobsleigh', 'boat rental', 'boules', 'bowling', 'bungee jumping', 'cabaret', 'canoe', 'canyoning', 'casino', 'cinema', 'climbing', 'concert hall', 'conference center', 'cooking class', 'cricket', 'cultural center', 'cycling', 'diving', 'dolphinarium', 'escape game', 'event', 'extreme sports', 'festival', 'fishing', 'fitness center', 'football pitch', 'gliding', 'golf', 'hiking', 'hillwalking', 'horse riding', 'ice rink', 'ice skating', 'ice stadium', 'indoor pool', 'kitesurfing', 'karting', 'leisure center', 'massage', 'mountain biking', 'outdoor pool', 'parachuting', 'paragliding', 'playground', 'public bath', 'rafting', 'ropes course', 'rowing', 'sailing', 'sandboarding', 'sauna', 'scuba diving', 'shooting range', 'skatepark', 'skiing', 'ski school', 'ski touring', 'skydiving', 'sledding', 'snorkeling', 'snowboarding', 'soccer', 'spa', 'squash', 'summer toboggan', 'surfing', 'swimming', 'tennis', 'theme park', 'toboggan', 'water park', 'water sports', 'wellness', 'wildlife observation', 'windsurfing', 'winter sports', 'yoga', 'zoo',],
//         'buy': ['antiquarian', 'bakery', 'bank', 'beverages', 'bike shop', 'book seller', 'boutique', 'butchery', 'car repair', 'carpet shop', 'chemist', 'clothes', 'collectibles', 'convenience', 'crafts shop', 'delicatessen', 'department store', 'duty-free shop', 'electronics', 'fashion store', 'florist', 'gift shop', 'grocery', 'hardware', 'jewellery', 'kiosk', 'mall', 'market', 'music shop', 'optician', 'outdoor retailer', 'pastry shop', 'perfumery', 'pet shop', 'photo store', 'second hand', 'shoe shop', 'shopping district', 'shopping street', 'souvenir shop', 'sports shop', 'supermarket', 'ticket shop', 'toys', 'vending machine', 'wine shop',],
//         'sleep': ['appartment', 'alpine hut', 'bed and bike', 'bnb', 'campsite', 'caravan site', 'chalet', 'ecolodge', 'guest house', 'hostel', 'hotel', 'hotel garni', 'holiday flat', 'motel', 'resort', 'wilderness hut', 'youth hostel', 'boarding house',],
//         'eat': ['bistro', 'brasserie', 'cafeteria', 'cafe', 'fast food', 'ice cream', 'pizzeria', 'restaurant', 'seafood restaurant', 'snack bar', 'street food', 'takeaway', 'tavern', 'teahouse',],
//         'drink': ['bar', 'beer garden', 'brewery', 'club', 'discotheque', 'nightclub', 'pub', 'wine bar',],
//         'listing': ['other', 'health', 'go', 'error', 'area', 'populated', 'religion',]
//     }
//
//     return mapping[type.toLowerCase()] || ['listing'];
// }